import type { MapLayer } from '../types'

export const DEFAULT_LAYERS: MapLayer[] = [
  // Military & Strategic
  {
    id: 'flights',
    name: 'Live Flights',
    category: 'military',
    icon: 'Plane',
    enabled: false,
    color: '#00d4aa',
  },
  {
    id: 'satellites',
    name: 'Satellites',
    category: 'military',
    icon: 'Satellite',
    enabled: false,
    color: '#8b5cf6',
  },
  {
    id: 'bases',
    name: 'Military Bases',
    category: 'military',
    icon: 'Shield',
    enabled: false,
    color: '#ef4444',
  },
  {
    id: 'nuclear',
    name: 'Nuclear Facilities',
    category: 'military',
    icon: 'Radiation',
    enabled: false,
    color: '#f59e0b',
  },
  {
    id: 'spaceports',
    name: 'Spaceports',
    category: 'military',
    icon: 'Rocket',
    enabled: false,
    color: '#6366f1',
  },

  // Infrastructure
  {
    id: 'cables',
    name: 'Undersea Cables',
    category: 'infrastructure',
    icon: 'Cable',
    enabled: false,
    color: '#3b82f6',
  },
  {
    id: 'pipelines',
    name: 'Oil/Gas Pipelines',
    category: 'infrastructure',
    icon: 'Pipette',
    enabled: false,
    color: '#a855f7',
  },
  {
    id: 'datacenters',
    name: 'AI Datacenters',
    category: 'infrastructure',
    icon: 'Server',
    enabled: false,
    color: '#06b6d4',
  },
  {
    id: 'ports',
    name: 'Strategic Ports',
    category: 'infrastructure',
    icon: 'Anchor',
    enabled: false,
    color: '#0ea5e9',
  },
  {
    id: 'outages',
    name: 'Internet Outages',
    category: 'infrastructure',
    icon: 'WifiOff',
    enabled: false,
    color: '#f43f5e',
  },

  // Conflicts & Unrest
  {
    id: 'conflicts',
    name: 'Conflict Zones',
    category: 'conflicts',
    icon: 'Crosshair',
    enabled: false,
    color: '#dc2626',
  },
  {
    id: 'protests',
    name: 'Protests & Unrest',
    category: 'conflicts',
    icon: 'Users',
    enabled: false,
    color: '#f97316',
  },
  {
    id: 'sanctions',
    name: 'Sanctions',
    category: 'conflicts',
    icon: 'Ban',
    enabled: false,
    color: '#b91c1c',
  },
  {
    id: 'displacement',
    name: 'Displacement',
    category: 'conflicts',
    icon: 'UserX',
    enabled: false,
    color: '#e11d48',
  },

  // Natural Events
  {
    id: 'earthquakes',
    name: 'Earthquakes',
    category: 'natural',
    icon: 'Activity',
    enabled: false,
    color: '#eab308',
  },
  {
    id: 'weather',
    name: 'Weather Alerts',
    category: 'natural',
    icon: 'CloudLightning',
    enabled: false,
    color: '#64748b',
  },
  {
    id: 'fires',
    name: 'Active Fires',
    category: 'natural',
    icon: 'Flame',
    enabled: false,
    color: '#ff6b35',
  },
  {
    id: 'disasters',
    name: 'Natural Disasters',
    category: 'natural',
    icon: 'AlertTriangle',
    enabled: false,
    color: '#facc15',
  },
  {
    id: 'climate',
    name: 'Climate Anomalies',
    category: 'natural',
    icon: 'Thermometer',
    enabled: false,
    color: '#22d3ee',
  },

  // Live Feeds
  {
    id: 'cctv',
    name: 'CCTV Cameras',
    category: 'live',
    icon: 'Camera',
    enabled: false,
    color: '#10b981',
  },
  {
    id: 'broadcasts',
    name: 'Live Broadcasts',
    category: 'live',
    icon: 'Radio',
    enabled: false,
    color: '#8b5cf6',
  },
  {
    id: 'webcams',
    name: 'Hotspot Webcams',
    category: 'live',
    icon: 'Video',
    enabled: false,
    color: '#14b8a6',
  },

  // Financial
  {
    id: 'exchanges',
    name: 'Stock Exchanges',
    category: 'financial',
    icon: 'TrendingUp',
    enabled: false,
    color: '#22c55e',
  },
  {
    id: 'centralbanks',
    name: 'Central Banks',
    category: 'financial',
    icon: 'Landmark',
    enabled: false,
    color: '#a78bfa',
  },
  {
    id: 'commodities',
    name: 'Commodity Hubs',
    category: 'financial',
    icon: 'BarChart3',
    enabled: false,
    color: '#fbbf24',
  },
]
